MAIN = "1"

CATEGORY = "2"

SWITCH = "3"

ADD_CMD = "4"

CMD_LIST = "5"

EDIT_CMD = "6"

EDIT_CMD_RESPONSE_TEXT = "7"

EDIT_CMD_NOTIFICATION_TEXT = "8"

SWITCH_CMD_NOTIFICATION = "9"

DEL_CMD = "10"

FP_LOTS_LIST = "11"

ADD_AD_TO_LOT = "12"

ADD_AD_TO_LOT_MANUALLY = "13"

AD_LOTS_LIST = "14"

EDIT_AD_LOT = "15"

EDIT_LOT_DELIVERY_TEXT = "16"

BIND_PRODUCTS_FILE = "17"

DEL_AD_LOT = "18"

PRODUCTS_FILES_LIST = "19"

EDIT_PRODUCTS_FILE = "20"

UPLOAD_PRODUCTS_FILE = "21"

CREATE_PRODUCTS_FILE = "22"

ADD_PRODUCTS_TO_FILE = "23"

DOWNLOAD_CFG = "24"

TMPLT_LIST = "25"

TMPLT_LIST_ANS_MODE = "26"

EDIT_TMPLT = "27"

DEL_TMPLT = "28"

ADD_TMPLT = "29"

SEND_TMPLT = "30"

SWITCH_TG_NOTIFICATIONS = "31"

REQUEST_REFUND = "32"

REFUND_CONFIRMED = "33"

REFUND_CANCELLED = "34"

BAN = "35"

UNBAN = "36"

SHUT_DOWN = "37"

CANCEL_SHUTTING_DOWN = "38"

SEND_FP_MESSAGE = "to_node"

UPLOAD_CHAT_IMAGE = "upload_chat_image"

UPLOAD_OFFER_IMAGE = "upload_offer_image"

UPLOAD_BACKUP = "upload_backup"

UPDATE_PROFILE = "39"

MANUAL_AD_TEST = "40"

CLEAR_STATE = "41"

BACK_TO_REPLY_KB = "42"

BACK_TO_ORDER_KB = "43"

PLUGINS_LIST = "44"

EDIT_PLUGIN = "45"

TOGGLE_PLUGIN = "46"

PLUGIN_SETTINGS = "47"

PLUGIN_COMMANDS = "48"

DELETE_PLUGIN = "49"

CANCEL_DELETE_PLUGIN = "50"

CONFIRM_DELETE_PLUGIN = "51"

UPLOAD_PLUGIN = "52"

PARAM_DISABLED = "53"

MAIN2 = "54"

EDIT_GREETINGS_TEXT = "55"

EDIT_ORDER_CONFIRM_REPLY_TEXT = "56"

SEND_REVIEW_REPLY_TEXT = "57"

EDIT_REVIEW_REPLY_TEXT = "58"

EDIT_WATERMARK = "59"

EXTEND_CHAT = "60"

OLD_MOD_HELP = "61"

EMPTY = "62"

LANG = "63"

EDIT_GREETINGS_COOLDOWN = "64"

CHANGE_GOLDEN_KEY = "65"

CONFIG_LOADER = "66"

AUTHORIZED_USERS = "67"

AUTHORIZED_USER_SETTINGS = "68"

PROXY = "69"

ADD_PROXY = "70"

CHOOSE_PROXY = "71"

DELETE_PROXY = "72"

CHANGE_PROXY_TYPE = "73"

SWITCH_PROXY_CHECK = "78"

MAIN3 = "79"

EDIT_ORDER_REMINDERS_TIMEOUT = "74"

EDIT_ORDER_REMINDERS_TEMPLATE = "75"

EDIT_ORDER_REMINDERS_REPEAT_COUNT = "76"

EDIT_ORDER_REMINDERS_INTERVAL = "77"

FP_LOT_EDIT_LIST = "80"

FP_LOT_EDIT = "81"

FP_LOT_EDIT_FIELD = "82"

FP_LOT_TOGGLE_ACTIVE = "83"

FP_LOT_TOGGLE_DEACTIVATE = "84"

FP_LOT_TOGGLE_AUTO_DELIVERY = "85"

FP_LOT_SAVE = "86"

UPDATE_FP_EDIT_LOTS = "87"

FP_LOT_CATEGORY_FIELDS = "88"

FP_LOT_EDIT_CATEGORY_FIELD = "89"

FP_LOT_DELETE = "90"

FP_LOT_CONFIRM_DELETE = "91"

FP_LOT_COPY_FIELD = "92"

FP_LOT_VIEW_DETAILS = "93"

FP_LOT_SELECT_OPTION = "94"

SEND_ALL_REMINDERS = "95"

EDIT_REVIEW_REMINDERS_TIMEOUT = "96"

EDIT_REVIEW_REMINDERS_TEMPLATE = "97"

EDIT_REVIEW_REMINDERS_REPEAT_COUNT = "98"

EDIT_REVIEW_REMINDERS_INTERVAL = "99"

SEND_ALL_REVIEW_REMINDERS = "100"

SUPPORT_TICKETS = "101"

SUPPORT_TICKETS_TOGGLE_AUTO = "102"

SUPPORT_TICKETS_SEND_NOW = "103"

SUPPORT_TICKETS_REFRESH = "114"

SUPPORT_TICKETS_SET_HOURS = "115"

SUPPORT_TICKETS_SET_TIME = "116"

LE_SEARCH_BY_LOT_ID = "104"

LE_SEARCH_BY_CATEGORY = "105"

LE_SEARCH_BY_TEXT = "106"

LE_CATEGORY_VIEW = "107"

LE_BULK_ACTIVATE = "108"

LE_BULK_DEACTIVATE = "109"

LE_BULK_DELETE = "110"

LE_BULK_CONFIRM = "111"

LE_SEARCH_MENU = "112"

LE_LOAD_CATEGORY_BY_ID = "113"

ACTIVITY_REFRESH = "117"

OR_CATEGORY_LIST = "118"

OR_CATEGORY_ADD = "119"

OR_CATEGORY_EDIT = "120"

OR_CATEGORY_DELETE = "121"

OR_CATEGORY_EDIT_TIMEOUT = "122"

OR_CATEGORY_EDIT_TEMPLATE = "123"

OR_CATEGORY_EDIT_REPEAT_COUNT = "124"

OR_CATEGORY_EDIT_INTERVAL = "125"

OR_CATEGORY_TOGGLE = "126"

GR_CATEGORY_LIST = "127"

GR_CATEGORY_ADD = "128"

GR_CATEGORY_EDIT = "129"

GR_CATEGORY_DELETE = "130"

GR_CATEGORY_EDIT_TEMPLATE = "131"

GR_CATEGORY_TOGGLE = "132"

GR_COPY_DEFAULT = "133"

TOGGLE_CMD_DISABLED = "134"

TOGGLE_PIN_PLUGIN = "135"

EDIT_TIMEZONE = "136"

TOGGLE_SCHEDULE = "137"
EDIT_SCHEDULE_HOURS = "138"
EDIT_SCHEDULE_MSG = "139"
TOGGLE_MUTE_CATEGORY = "140"
BULK_LOTS_ACTIVATE = "141"
BULK_LOTS_DEACTIVATE = "142"
TOGGLE_DISCOUNT = "143"
CANCEL_DISCOUNT = "144"
CANCEL_ALL_DISCOUNTS = "145"

# Новые callback-пространства Sigma 2.14. Старые числовые значения не меняются:
# плагины Cardinal и сохранённые inline-клавиатуры продолжают работать.
DASHBOARD = "sigma.dashboard"
DASHBOARD_REFRESH = "sigma.dashboard.refresh"
SALES = "sigma.sales"
SALES_REFRESH = "sigma.sales.refresh"
COPY_ORDER_ID = "sigma.sales.copy"
LOT_HEALTH = "sigma.lot_health"
LOT_HEALTH_REFRESH = "sigma.lot_health.refresh"
NOTIFICATION_DIGEST = "sigma.notifications.digest"
